---
title: "R Notebook"
output: html_document
author: "Dhruv Dole, Ahmed Gharib"
---
```{r}
library(tidyverse)
raw_data <- read.csv("https://raw.githubusercontent.com/dsdole/DS202Final/main/data/Expanded_data_with_more_features.csv")
```
```{r}
raw_data
raw_data$Gender <- as.factor(raw_data$Gender)
raw_data$EthnicGroup <- as.factor(raw_data$EthnicGroup)
raw_data$ParentEduc <- as.factor(raw_data$EthnicGroup)
raw_data$LunchType <- as.factor(raw_data$LunchType)
raw_data$TestPrep <- as.factor(raw_data$TestPrep)
raw_data$ParentMaritalStatus <- as.factor(raw_data$ParentMaritalStatus)
raw_data$isFirstChild <- as.factor(raw_data$isFirstChild)
raw_data$TransportMeans <- as.factor(raw_data$TransportMeans)
unique(raw_data$WklyStudyHours)
```

```{r}
head(raw_data)
```
# Erasing "X" from the dataset:
```{r}
library(dplyr)

raw_data <- select(raw_data, -X)
head(raw_data)
```
#Replacing empty space in the dataset with "N/A":
```{r}
raw_data <- raw_data %>%
  mutate_all(~ na_if(.,"")) %>% # replace empty strings with NA values
  mutate_all(~ ifelse(is.na(.), "N/A", .)) # replace NA values with "N/A"

head(raw_data)
```

